// Code generated by tygo. DO NOT EDIT.
// Code generated by tygo from internal/domain. DO NOT EDIT.
// Regenerate with: backend/tools/gen-types.sh
// Service response aggregates (PeriodSummary, PeriodTrends, ...) are
// hand-maintained in types.ts because they reference these entities
// across packages, which tygo cannot resolve into a single file.

//////////
// source: budget.go

/**
 * BudgetLine is one subcategory row of the budget report.
 */
export interface BudgetLine {
  categoryId: string;
  subcategory: string;
  budget: number /* int64 */;
  actual: number /* int64 */;
  remaining: number /* int64 */;
}
/**
 * CategoryRollup aggregates all lines of one category.
 */
export interface CategoryRollup {
  categoryId: string;
  budget: number /* int64 */;
  actual: number /* int64 */;
  remaining: number /* int64 */;
}
/**
 * BudgetTotals mirrors the Excel Total / Cash / Non-Cash footer.
 */
export interface BudgetTotals {
  budget: number /* int64 */;
  actual: number /* int64 */;
  remaining: number /* int64 */;
  cashActual: number /* int64 */;
  nonCashActual: number /* int64 */;
}
/**
 * BudgetReportResult is the full budget-vs-actual view for a period.
 */
export interface BudgetReportResult {
  lines: BudgetLine[];
  categories: CategoryRollup[];
  totals: BudgetTotals;
}

//////////
// source: models.go

export interface User {
  id: string;
  name: string;
  email: string;
  phone?: string;
  createdAt: string;
}
export interface Subcategory {
  name: string;
  active: boolean;
}
export type CategoryKind = string;
export const CategoryExpense: CategoryKind = "expense";
export const CategorySavings: CategoryKind = "savings";
export const CategoryPay: CategoryKind = "pay";
export interface Category {
  id: string;
  name: string;
  kind: CategoryKind;
  subcategories: Subcategory[];
  active: boolean;
}
export type AccountKind = string;
export const AccountBank: AccountKind = "bank";
export const AccountMobile: AccountKind = "mobile";
export const AccountCash: AccountKind = "cash";
export const AccountSavings: AccountKind = "savings";
export const AccountVirtual: AccountKind = "virtual";
export type VirtualRole = string;
export const RoleExternal: VirtualRole = "external"; // "Add" — money entering the system
export const RoleLendGiven: VirtualRole = "lendGiven";
export const RoleLendTaken: VirtualRole = "lendTaken";
export interface Account {
  id: string;
  name: string;
  kind: AccountKind;
  virtualRole?: VirtualRole;
  active: boolean;
  goal?: number /* int64 */; // savings target in paisa, 0 = none
}
export interface AccountAmount {
  accountId: string;
  amount: number /* int64 */;
}
export type PeriodStatus = string;
export const PeriodOpen: PeriodStatus = "open";
export const PeriodClosed: PeriodStatus = "closed";
export interface Period {
  id: string;
  name: string;
  startDate: string;
  endDate: string;
  status: PeriodStatus;
  openingBalances: AccountAmount[];
  openingSavings: AccountAmount[];
  previousPeriodId?: string;
}
export interface Expense {
  id: string;
  periodId: string;
  date: string;
  categoryId: string;
  subcategory: string;
  accountId: string; // payment method
  amount: number /* int64 */;
  breakdown?: number /* int64 */[];
  remarks?: string;
}
export interface Transfer {
  id: string;
  periodId: string;
  date: string;
  fromAccountId: string;
  toAccountId: string;
  amount: number /* int64 */;
  fee: number /* int64 */;
  note?: string;
}
export interface BudgetItem {
  categoryId: string;
  subcategory: string;
  amount: number /* int64 */;
}
export interface Budget {
  id: string;
  periodId: string;
  items: BudgetItem[];
  rollover: boolean; // carry previous period's unspent budget forward
}
export type LendType = string;
export const LendGiven: LendType = "given";
export const LendTaken: LendType = "taken";
export type LendStatus = string;
export const LendOpen: LendStatus = "open";
export const LendSettled: LendStatus = "settled";
export interface Settlement {
  date: string;
  amount: number /* int64 */;
  note?: string;
}
export interface Lend {
  id: string;
  type: LendType;
  person: string;
  date: string;
  amount: number /* int64 */;
  settlements: Settlement[];
  status: LendStatus;
  notes?: string;
}
export interface PaymentWindow {
  id: string;
  periodId: string;
  name: string;
  categoryId?: string;
  subcategory?: string;
  startDate: string;
  endDate: string;
}
export interface Reminder {
  id: string;
  date: string;
  task: string;
  done: boolean;
}
/**
 * RecurringExpense is a reusable expense template (rent, utilities, fees)
 * the user can drop into any period with one tap.
 */
export interface RecurringExpense {
  id: string;
  label: string;
  categoryId: string;
  subcategory: string;
  accountId: string;
  amount: number /* int64 */;
}

//////////
// source: window.go

export type WindowState = string;
export const WindowUpcoming: WindowState = "upcoming";
export const WindowActive: WindowState = "active";
export const WindowExpired: WindowState = "expired";
export const WindowPaid: WindowState = "paid";
/**
 * WindowStatusResult describes a payment window relative to today.
 * Days means: upcoming → days until start; active → days left; expired → days since end.
 */
export interface WindowStatusResult {
  state: WindowState;
  days: number /* int */;
  paidAmount: number /* int64 */;
}
